name: Deploy Static Site to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        run: |
          # Crear (o cambiar a) la rama gh-pages sin historial previo
          git checkout --orphan gh-pages
          
          # Eliminar archivos antiguos de la rama gh-pages
          git rm -rf .
          
          # Copiar solo los archivos estáticos necesarios
          cp -r * .github .. # Copia todos los archivos excepto .git
          rm -rf .github # Eliminamos la carpeta del workflow

          # Confirmar y subir cambios a gh-pages
          git add .
          git commit -m "Deploy static site to GitHub Pages"
          git push --force origin gh-pages

